/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminComplaintsRouteImport } from './routes/admin.complaints'
import { Route as AdminIssuesRouteImport } from './routes/admin.issues'
import { Route as AdminRulesRouteImport } from './routes/admin.rules'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CitizenIndexRouteImport } from './routes/citizen.index'
import { Route as CitizenHistoryRouteImport } from './routes/citizen.history'
import { Route as CitizenNewRouteImport } from './routes/citizen.new'
import { Route as CitizenProfileRouteImport } from './routes/citizen.profile'
import { Route as CitizenTrackRouteImport } from './routes/citizen.track'
import { Route as OfficerIndexRouteImport } from './routes/officer.index'
import { Route as OfficerIssuesRouteImport } from './routes/officer.issues'
import { Route as OfficerLogsRouteImport } from './routes/officer.logs'
import { Route as OfficerMapRouteImport } from './routes/officer.map'
import { Route as OfficerProfileRouteImport } from './routes/officer.profile'
import { Route as OfficerTrackRouteImport } from './routes/officer.track'
import { Route as CitizenComplaintTicketRouteImport } from './routes/citizen.complaint.$ticket'
import { Route as OfficerIssueIssueIdRouteImport } from './routes/officer.issue.$issueId'
import { Route as OfficerValidateTicketRouteImport } from './routes/officer.validate.$ticket'
import { Route as ApiPublicN8nDispatchRouteImport } from './routes/api/public/n8n.dispatch'
import { Route as ApiPublicN8nTriageRouteImport } from './routes/api/public/n8n.triage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIssuesRoute = AdminIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRulesRoute = AdminRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenHistoryRoute = CitizenHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenNewRoute = CitizenNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenProfileRoute = CitizenProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CitizenRoute,
} as any)
const CitizenTrackRoute = CitizenTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => CitizenRoute,
} as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerIssuesRoute = OfficerIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerLogsRoute = OfficerLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerMapRoute = OfficerMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerProfileRoute = OfficerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerTrackRoute = OfficerTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => OfficerRoute,
} as any)
const CitizenComplaintTicketRoute = CitizenComplaintTicketRouteImport.update({
  id: '/complaint/$ticket',
  path: '/complaint/$ticket',
  getParentRoute: () => CitizenRoute,
} as any)
const OfficerIssueIssueIdRoute = OfficerIssueIssueIdRouteImport.update({
  id: '/issue/$issueId',
  path: '/issue/$issueId',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerValidateTicketRoute = OfficerValidateTicketRouteImport.update({
  id: '/validate/$ticket',
  path: '/validate/$ticket',
  getParentRoute: () => OfficerRoute,
} as any)
const ApiPublicN8nDispatchRoute = ApiPublicN8nDispatchRouteImport.update({
  id: '/api/public/n8n/dispatch',
  path: '/api/public/n8n/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicN8nTriageRoute = ApiPublicN8nTriageRouteImport.update({
  id: '/api/public/n8n/triage',
  path: '/api/public/n8n/triage',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/automation': typeof AutomationRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/officer': typeof OfficerRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/issues': typeof AdminIssuesRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/citizen/history': typeof CitizenHistoryRoute
  '/citizen/new': typeof CitizenNewRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/track': typeof CitizenTrackRoute
  '/officer/issues': typeof OfficerIssuesRoute
  '/officer/logs': typeof OfficerLogsRoute
  '/officer/map': typeof OfficerMapRoute
  '/officer/profile': typeof OfficerProfileRoute
  '/officer/track': typeof OfficerTrackRoute
  '/admin/': typeof AdminIndexRoute
  '/citizen/': typeof CitizenIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/citizen/complaint/$ticket': typeof CitizenComplaintTicketRoute
  '/officer/issue/$issueId': typeof OfficerIssueIssueIdRoute
  '/officer/validate/$ticket': typeof OfficerValidateTicketRoute
  '/api/public/n8n/dispatch': typeof ApiPublicN8nDispatchRoute
  '/api/public/n8n/triage': typeof ApiPublicN8nTriageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automation': typeof AutomationRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/issues': typeof AdminIssuesRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/citizen/history': typeof CitizenHistoryRoute
  '/citizen/new': typeof CitizenNewRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/track': typeof CitizenTrackRoute
  '/officer/issues': typeof OfficerIssuesRoute
  '/officer/logs': typeof OfficerLogsRoute
  '/officer/map': typeof OfficerMapRoute
  '/officer/profile': typeof OfficerProfileRoute
  '/officer/track': typeof OfficerTrackRoute
  '/admin': typeof AdminIndexRoute
  '/citizen': typeof CitizenIndexRoute
  '/officer': typeof OfficerIndexRoute
  '/citizen/complaint/$ticket': typeof CitizenComplaintTicketRoute
  '/officer/issue/$issueId': typeof OfficerIssueIssueIdRoute
  '/officer/validate/$ticket': typeof OfficerValidateTicketRoute
  '/api/public/n8n/dispatch': typeof ApiPublicN8nDispatchRoute
  '/api/public/n8n/triage': typeof ApiPublicN8nTriageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/automation': typeof AutomationRoute
  '/citizen': typeof CitizenRouteWithChildren
  '/officer': typeof OfficerRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/issues': typeof AdminIssuesRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/citizen/history': typeof CitizenHistoryRoute
  '/citizen/new': typeof CitizenNewRoute
  '/citizen/profile': typeof CitizenProfileRoute
  '/citizen/track': typeof CitizenTrackRoute
  '/officer/issues': typeof OfficerIssuesRoute
  '/officer/logs': typeof OfficerLogsRoute
  '/officer/map': typeof OfficerMapRoute
  '/officer/profile': typeof OfficerProfileRoute
  '/officer/track': typeof OfficerTrackRoute
  '/admin/': typeof AdminIndexRoute
  '/citizen/': typeof CitizenIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/citizen/complaint/$ticket': typeof CitizenComplaintTicketRoute
  '/officer/issue/$issueId': typeof OfficerIssueIssueIdRoute
  '/officer/validate/$ticket': typeof OfficerValidateTicketRoute
  '/api/public/n8n/dispatch': typeof ApiPublicN8nDispatchRoute
  '/api/public/n8n/triage': typeof ApiPublicN8nTriageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/automation'
    | '/citizen'
    | '/officer'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/complaints'
    | '/admin/issues'
    | '/admin/rules'
    | '/admin/users'
    | '/citizen/history'
    | '/citizen/new'
    | '/citizen/profile'
    | '/citizen/track'
    | '/officer/issues'
    | '/officer/logs'
    | '/officer/map'
    | '/officer/profile'
    | '/officer/track'
    | '/admin/'
    | '/citizen/'
    | '/officer/'
    | '/citizen/complaint/$ticket'
    | '/officer/issue/$issueId'
    | '/officer/validate/$ticket'
    | '/api/public/n8n/dispatch'
    | '/api/public/n8n/triage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/automation'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/complaints'
    | '/admin/issues'
    | '/admin/rules'
    | '/admin/users'
    | '/citizen/history'
    | '/citizen/new'
    | '/citizen/profile'
    | '/citizen/track'
    | '/officer/issues'
    | '/officer/logs'
    | '/officer/map'
    | '/officer/profile'
    | '/officer/track'
    | '/admin'
    | '/citizen'
    | '/officer'
    | '/citizen/complaint/$ticket'
    | '/officer/issue/$issueId'
    | '/officer/validate/$ticket'
    | '/api/public/n8n/dispatch'
    | '/api/public/n8n/triage'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/automation'
    | '/citizen'
    | '/officer'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/complaints'
    | '/admin/issues'
    | '/admin/rules'
    | '/admin/users'
    | '/citizen/history'
    | '/citizen/new'
    | '/citizen/profile'
    | '/citizen/track'
    | '/officer/issues'
    | '/officer/logs'
    | '/officer/map'
    | '/officer/profile'
    | '/officer/track'
    | '/admin/'
    | '/citizen/'
    | '/officer/'
    | '/citizen/complaint/$ticket'
    | '/officer/issue/$issueId'
    | '/officer/validate/$ticket'
    | '/api/public/n8n/dispatch'
    | '/api/public/n8n/triage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  AutomationRoute: typeof AutomationRoute
  CitizenRoute: typeof CitizenRouteWithChildren
  OfficerRoute: typeof OfficerRouteWithChildren
  ApiPublicN8nDispatchRoute: typeof ApiPublicN8nDispatchRoute
  ApiPublicN8nTriageRoute: typeof ApiPublicN8nTriageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/issues': {
      id: '/admin/issues'
      path: '/issues'
      fullPath: '/admin/issues'
      preLoaderRoute: typeof AdminIssuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rules': {
      id: '/admin/rules'
      path: '/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminRulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/history': {
      id: '/citizen/history'
      path: '/history'
      fullPath: '/citizen/history'
      preLoaderRoute: typeof CitizenHistoryRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/new': {
      id: '/citizen/new'
      path: '/new'
      fullPath: '/citizen/new'
      preLoaderRoute: typeof CitizenNewRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/profile': {
      id: '/citizen/profile'
      path: '/profile'
      fullPath: '/citizen/profile'
      preLoaderRoute: typeof CitizenProfileRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/citizen/track': {
      id: '/citizen/track'
      path: '/track'
      fullPath: '/citizen/track'
      preLoaderRoute: typeof CitizenTrackRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/officer/': {
      id: '/officer/'
      path: '/'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/issues': {
      id: '/officer/issues'
      path: '/issues'
      fullPath: '/officer/issues'
      preLoaderRoute: typeof OfficerIssuesRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/logs': {
      id: '/officer/logs'
      path: '/logs'
      fullPath: '/officer/logs'
      preLoaderRoute: typeof OfficerLogsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/map': {
      id: '/officer/map'
      path: '/map'
      fullPath: '/officer/map'
      preLoaderRoute: typeof OfficerMapRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/profile': {
      id: '/officer/profile'
      path: '/profile'
      fullPath: '/officer/profile'
      preLoaderRoute: typeof OfficerProfileRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/track': {
      id: '/officer/track'
      path: '/track'
      fullPath: '/officer/track'
      preLoaderRoute: typeof OfficerTrackRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/citizen/complaint/$ticket': {
      id: '/citizen/complaint/$ticket'
      path: '/complaint/$ticket'
      fullPath: '/citizen/complaint/$ticket'
      preLoaderRoute: typeof CitizenComplaintTicketRouteImport
      parentRoute: typeof CitizenRoute
    }
    '/officer/issue/$issueId': {
      id: '/officer/issue/$issueId'
      path: '/issue/$issueId'
      fullPath: '/officer/issue/$issueId'
      preLoaderRoute: typeof OfficerIssueIssueIdRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/validate/$ticket': {
      id: '/officer/validate/$ticket'
      path: '/validate/$ticket'
      fullPath: '/officer/validate/$ticket'
      preLoaderRoute: typeof OfficerValidateTicketRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/api/public/n8n/dispatch': {
      id: '/api/public/n8n/dispatch'
      path: '/api/public/n8n/dispatch'
      fullPath: '/api/public/n8n/dispatch'
      preLoaderRoute: typeof ApiPublicN8nDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/n8n/triage': {
      id: '/api/public/n8n/triage'
      path: '/api/public/n8n/triage'
      fullPath: '/api/public/n8n/triage'
      preLoaderRoute: typeof ApiPublicN8nTriageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminIssuesRoute: typeof AdminIssuesRoute
  AdminRulesRoute: typeof AdminRulesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminIssuesRoute: AdminIssuesRoute,
  AdminRulesRoute: AdminRulesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CitizenRouteChildren {
  CitizenHistoryRoute: typeof CitizenHistoryRoute
  CitizenNewRoute: typeof CitizenNewRoute
  CitizenProfileRoute: typeof CitizenProfileRoute
  CitizenTrackRoute: typeof CitizenTrackRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
  CitizenComplaintTicketRoute: typeof CitizenComplaintTicketRoute
}

const CitizenRouteChildren: CitizenRouteChildren = {
  CitizenHistoryRoute: CitizenHistoryRoute,
  CitizenNewRoute: CitizenNewRoute,
  CitizenProfileRoute: CitizenProfileRoute,
  CitizenTrackRoute: CitizenTrackRoute,
  CitizenIndexRoute: CitizenIndexRoute,
  CitizenComplaintTicketRoute: CitizenComplaintTicketRoute,
}

const CitizenRouteWithChildren =
  CitizenRoute._addFileChildren(CitizenRouteChildren)

interface OfficerRouteChildren {
  OfficerIssuesRoute: typeof OfficerIssuesRoute
  OfficerLogsRoute: typeof OfficerLogsRoute
  OfficerMapRoute: typeof OfficerMapRoute
  OfficerProfileRoute: typeof OfficerProfileRoute
  OfficerTrackRoute: typeof OfficerTrackRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
  OfficerIssueIssueIdRoute: typeof OfficerIssueIssueIdRoute
  OfficerValidateTicketRoute: typeof OfficerValidateTicketRoute
}

const OfficerRouteChildren: OfficerRouteChildren = {
  OfficerIssuesRoute: OfficerIssuesRoute,
  OfficerLogsRoute: OfficerLogsRoute,
  OfficerMapRoute: OfficerMapRoute,
  OfficerProfileRoute: OfficerProfileRoute,
  OfficerTrackRoute: OfficerTrackRoute,
  OfficerIndexRoute: OfficerIndexRoute,
  OfficerIssueIssueIdRoute: OfficerIssueIssueIdRoute,
  OfficerValidateTicketRoute: OfficerValidateTicketRoute,
}

const OfficerRouteWithChildren =
  OfficerRoute._addFileChildren(OfficerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  AutomationRoute: AutomationRoute,
  CitizenRoute: CitizenRouteWithChildren,
  OfficerRoute: OfficerRouteWithChildren,
  ApiPublicN8nDispatchRoute: ApiPublicN8nDispatchRoute,
  ApiPublicN8nTriageRoute: ApiPublicN8nTriageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
